### ISSUE TITLE
Fellow or fellows, individual or team?

### ISSUE THREAD

**Issue by mlinksva** [basselkhartabil/basselkhartabil.org#11]
Friend looking at the site closely pointed out:

> How many fellowships will there be? Site speaks of "an outstanding individual" but also "fellows".

Along those lines, also:

> The Fellowship is open to individuals and small teams worldwide

If teams can apply maybe that should be included consistently throughout.

**Comment by mlinksva** [comment]
1 fellowship to be awarded, can be awarded to an individual or team. Accurate? If not, what is? PR to follow confirmation. 😁

**Comment by rejon** [comment]
i think so
